version: 2

name: Faidon Tsetsis
title: Undergraduate Student
email: p18tset1@ionio.gr
website: https://github.com/FaidonTsetsis

darkmode: true

github_username:  FaidonTsetsis

about_profile_image: images/bioprog.jpeg 
about_content: | # this will include new lines to allow paragraphs
  Hey my name is Faidon, I am currently 21 years old and I am a junior developer in the field of computer science. My nationality is greek and I am studying at Ionian University, located in the island of Corfu. 

content:
      
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Newbie Developer
        ub_title: Practising since 2018
   
       
        description: | # this will include new lines to allow paragraphs
         
          - Physical Languages:<br>
          English certification of proficiency - C2 ESB (International)


          - Programming Languages:<br>
          I have worked with JavaScript, C, C++, Python, SQL, PhP
          
          
          - Tools:<br>
          Docker, Xampp, mySQL
          
          
          - Operating Systems:<br>
          Microsoft Windows (8.1/10), Linux Ubuntu, Unix (very basic structure) 
          
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Ionian University
        sub_title: Department of Computer Science
        caption: Date Range 2018-2022
        #quote: >
        #  Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - Undergraduate student of computer science - University of Ionian Islands
          
          - Participator student of Python Workshop, hosted by Ionian University within a period of a semester
          
          - Participation in MLH-hackathon hosted by Github - infrastructural supported by Ionian University
          
          - Cryptography workshop hosted by Ionian University for a weekend

footer_show_references: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
