version: 2

name: Faidon Tsetsis
title: Undergraduate Student
email: fedon.tsetsis@gmail.com
website: https://github.com/FaidonTsetsis

darkmode: true

github_username:  FaidonTsetsis
#about_profile_image: images/bioprog.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hey my name is Faidon, I am 22 years old (18.03.2000) and I am a junior developer in the field of computer science. I have been studying for the past four years as a undergraduate student at Ionian University, and most of my experience is based on Website building.

content:
- layout: top-left
        title: Ionian University
        sub_title: Department of Computer Science
        caption: Date Range 2018-2022
      
  - title: Education
    layout: list
        description: | # this will include new lines to allow paragraphs
         
            
          - Undergraduate student of computer science - University of Ionian Islands
          
          - Participator student of Python Workshop, hosted by Ionian University within a period of a semester
          
          - Participation in MLH-hackathon hosted by Github - infrastructural supported by Ionian University
          
          - Cryptography workshop hosted by Ionian University for a weekend
          
          - English certification of proficiency - C2 ESB (International)
          
  - title: Experience
    layout: list
    content:
     
        #quote: >
        #  Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - Worked as an intern in a digital privacy policy making project called "tilderist"


          - Created projects based on WordPress & Carrd.co 
          
          
          - Familiarity with tools:<br>
          Docker, Xampp, mySQL
          
          
          - Operating Systems:<br>
          Microsoft Windows (8.1/10), Linux Ubuntu, Unix (very basic structure)



sass:
  sass_dir: _sass
  style: compressed

#plugins:
 #- jekyll-seo-tag

