# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Faidon Tsetsis
title: Undergraduate Student
email: p18tset1@ionio.gr
# email_title: Email (Email title override)
# phone: 
# phone_title: Phone (Phone title override)
website: https://github.com/FaidonTsetsis
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  FaidonTsetsis
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/bioprog.jpeg 
about_content: | # this will include new lines to allow paragraphs
  Hey my name is Faidon, I am currently 21 years old and I am a junior developer in the field of computer science. My nationality is greek and I am studying at Ionian University, located in the island of Corfu. 

content:
 - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
            
        description: | # this will include new lines to allow paragraphs
          - Turing Test, made in C
          
          - WebSite Development, made in JavaScript, PhP, mySQL
   

        
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Newbie Developer
        ub_title: Practising since 2018
   
       
        description: | # this will include new lines to allow paragraphs
         
          - Physical Languages:<br>
          English certification of proficiency - C2 ESB (International)


          - Programming Languages:<br>
          I have worked with JavaScript, C, C++, Python, SQL, PhP
          
          
          - Tools:<br>
          Docker, Xampp, mySQL
          
          
          - Operating Systems:<br>
          Microsoft Windows (8.1/10), Linux Ubuntu, Unix (very basic structure) 
          
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Ionian University
        sub_title: Department of Computer Science
        caption: Date Range 2018-2022
        #quote: >
        #  Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - Undergraduate student of computer science - University of Ionian Islands
          
          - Participator student of Python Workshop, hosted by Ionian University within a period of a semester
          
          - Participation in MLH-hackathon hosted by Github - infrastructural supported by Ionian University
          
          - Cryptography workshop hosted by Ionian University for a weekend

 
  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
    #  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

   #   Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
